export default defineEventHandler(async (event) => {
  await requireAuth(event, 'stock.view')
  const range = parseQuery(event, dateRangeQuery)
  const created = dateFilter(range)
  const rows = await ReceiptModel.find(created ? { createdAt: created } : {})
    .sort({ createdAt: -1 })
    .limit(500)
    .populate('supplier', 'name type phone')
    .populate('location', LOCATION_REF)
    .populate('user', USER_REF)
    .populate('lines.item', ITEM_REF)
    .lean()
  return ok(rows)
})
